/* History */
export const HISTORY_GO_BACK = 'HISTORY_GO_BACK';
export const HISTORY_GO_BACK_SUCCESS = 'HISTORY_GO_BACK_SUCCESS';
export const HISTORY_GO_BACK_FAILED = 'HISTORY_GO_BACK_FAILED';
export const NAVIGATE_TO_PATH = 'NAVIGATE_TO_PATH';

/* Clipboard */
export const INIT_CLIPBOARD_SUPPORT = 'INIT_CLIPBOARD_SUPPORT';
export const SUPPORT_CLIPBOARD = 'SUPPORT_CLIPBOARD';
export const DO_NOT_SUPPORT_CLIPBOARD = 'DO_NOT_SUPPORT_CLIPBOARD';
export const COPY_TEXT = 'COPY_TEXT';
export const COPY_TEXT_SUCCESS = 'COPY_TEXT_SUCCESS';
export const COPY_TEXT_FAILED = 'COPY_TEXT_FAILED';

/* Print */
export const PRINT = 'PRINT';
export const PRINT_SUCCESS = 'PRINT_SUCCESS';
export const PRINT_FAILED = 'PRINT_FAILED';

/* Input */
export const INPUT_KEYWORD = 'INPUT_KEYWORD';

/* Menu */
export const OPEN_MENU = 'OPEN_MENU';
export const CLOSE_MENU = 'CLOSE_MENU';
export const OPEN_SUB_MENU = 'OPEN_SUB_MENU';
export const CLOSE_SUB_MENU = 'CLOSE_SUB_MENU';
